# Generated by Django 3.2.16 on 2023-09-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230915_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descriptions',
            field=models.TextField(max_length=255),
        ),
    ]
